config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  post 'task_status_update', to: 'tasks#status_update'
  post 'add_label', to: 'tasks#add_label'
  post 'remove_label', to: 'tasks#remove_label'

  resources :labels  
  resources :users
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :admin do
    get '/', to: 'home#index'
    resources :users do
      resources :tasks, only: [:index]
    end
    resources :labels, only: [:index, :delete]
  end

  get '*anything', to: 'errors#routing_error'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :labels, through: :task_labels

  include AASM
  enum priority: {low: 0, normal: 1, high: 2}

  validates :title, :content, :end_period, :priority, presence: true
  validates :title, length: { maximum: 30 }
  validates :content, length: { maximum: 500 }
  validate :end_period_check, on: :create

  aasm column: :status do
    state :waiting,initial: true
    state :working 
    state :completed

    event :work do
      transitions from: :waiting, to: :working
    end

    event :complete do
      transitions from: :working, to: :completed
    end

  end

  def transitionable_state_option_by
    [[I18n.t("view.tasks.#{status}"), '']].concat(self.aasm.events.map(&:name).map{|state| [I18n.t("view.tasks.#{state}"), state] })
  end

  private

    def end_period_check
      if self.end_period.present?
        errors.add(:end_period, I18n.t('model.tasks.end_period_error_message')) unless self.end_period > Time.now
      end
    end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::BaseController
  before_action :logged_in_user
  
  def index
   @user = User.find(params[:user_id])
   @q = @user.tasks.search(params[:q] || {s: 'created_at desc'})
   @tasks = @q.result(distinct: true).page(params[:page])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :load_task, only: [:edit, :destroy, :update, :status_update, :add_label, :remove_label]
  before_action :load_priorities, only: [:edit, :new, :create, :update]

  def index
    @q = current_user.tasks.includes(:labels).search(params[:q] || {s: 'created_at desc'})
    @tasks = @q.result(distinct: true).page(params[:page])
    @status = Task.aasm.states.map(&:name)
    @labels = Label.all
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = t('controller.tasks.create_message', title: @task.title)
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update
    if @task.update_attributes(task_params)
      flash[:success] = t('controller.tasks.update_message', title: @task.title)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:success] = t('controller.tasks.destroy_message')
    redirect_to action: 'index'
  end

  def status_update
    @task.send(params[:status_select])
    @task.save!
    redirect_to action: 'index'
  end

  def add_label
    @task.task_labels.create(label_id: params[:label_id])
    redirect_to action: 'index'
  end

  def remove_label
    @task.task_labels.find_by(label_id: params[:label_id]).destroy
    redirect_to action: 'index'
  end

  private
    def task_params
      params.require(:task).permit(:title, :content, :end_period, :priority)
    end

    def load_task
      @task = Task.find(params[:id])
    end

    def load_priorities
      @priorities = Task.priorities.keys
    end  
  
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for @task do |f|
  = render 'shared/error_messages', object: f.object
  
  .form-group
    = f.label :title, t('view.tasks.title')
    = f.text_field :title , class: 'form-control'

  .form-group
    = f.label :content, t('view.tasks.content')
    = f.text_area :content , class: 'form-control'

  .form-group
    = f.label :end_period, t('view.tasks.end_period')
    = f.date_select :end_period , class: 'form-form-control date-picker' 

  - if controller.action_name == 'edit'
    .form-group
      = f.label :status, t("view.tasks.status")
      = f.select :status, options_for_select(@task.transitionable_state_option_by, @task.status)

  .form-group
    = f.label :priority, t("view.tasks.priority")
    = f.select :priority, options_for_select(@priorities.map{|priority| [t("view.tasks.priorities.#{priority}"), priority]}, selected: @task.priority)

  = f.submit t('view.tasks.create'), class: 'btn btn-success btn-block'

app/views/tasks/_search_form.html.haml
.modal.fade#myModal
  .modal-dialog
    .modal-content
      = search_form_for @q do |f|
        .modal-header.text-center
          = t('view.tasks.condition_search')
        .modal-body
          .form-group
            = f.label :title_cont, t('view.tasks.title')
            = f.search_field :title_cont
          .form-group
            = f.label :status, t('view.tasks.status')
            = f.select :status_eq, @status.map{|s| [t("view.tasks.#{s}"),s]}, include_blank: true
          .form-group
            = f.label :end_period, t('view.tasks.end_period')
            = f.date_select :end_period_gteq, include_blank: true
            = '〜'
            = f.date_select :end_period_lteq, include_blank: true
          .form_group.labels
            = f.label :labels_id_in, 'ラベル'
            .panels
              = f.collection_check_boxes :labels_id_in, @labels, :id, :name do |b|
                .label_panel{class: "#{b.object.color}", style: 'width: 23%'}
                  = b.label{b.check_box + '　' + b.text}
        .modal-footer
          .btn.btn-default{'data-dismiss': 'modal'}
            = t('view.tasks.close')
          = f.submit class: 'btn btn-default'

app/views/tasks/_select_labels.html.haml
.modal.fade{id: "label_list_#{task.id}"}
  .modal-dialog
    .modal-content
      .modal-header.text-center
        = "「#{task.title}」に付与するラベルを選択"
      .modal-body.labels
        .panels
          - select_labels = @labels - task.labels
          - select_labels.each do |label|
            .label_submit
              = link_to label.name, add_label_path(id: task.id, label_id: label.id), method: :post, class: "label_panel #{label.color}", data: {disable_with: '追加中...'}

      .modal-footer
        .btn.btn-default{'data-dismiss': 'modal'}
          = t('view.tasks.close')

app/views/tasks/edit.html.haml
- provide(:title, t('view.tasks.edit_page'))

= render 'form'
= link_to t('view.tasks.back'), root_path, class: 'btn btn-default btn-block'

app/views/tasks/index.html.haml
- provide(:title, t('view.tasks.index_page'))

= link_to t('view.tasks.new'), new_task_path, class: 'btn btn-primary btn-lg pull-right'
= link_to t('view.tasks.clear'), request.path, class: "btn btn-default btn-lg pull-right"
.btn.btn-primary.btn-lg.pull-right{'data-target': "#myModal", 'data-toggle': 'modal'}
  %i.fa.fa-external-link
  = t('view.tasks.condition_search')

.task_list
  %table.table.table-striped.table-hover.table-responsive
    %thead
      %tr
        %th= 'ラベル'
        %th= sort_link(@q, :title, t('view.tasks.title')) 
        %th= t('view.tasks.status')
        %th= sort_link(@q, :priority, t('view.tasks.priority'))
        %th= sort_link(@q, :end_period, t('view.tasks.end_period'))
        %th= sort_link(@q, :created_at, t('view.tasks.created_at')) 
        %th
        %th          
    %tbody
      - @tasks.each do |task|
        = render partial: 'select_labels', locals: {task: task}
        %tr
          %td.labels{style: "width: 180px;"}
            - task.labels.each do |label|
              .pull-left.label_panel{class: "#{label.color}", style: "width: 70%;"}
                = "#{label.name}　"
                = link_to fa_icon('trash lg'), remove_label_path(id: task.id, label_id: label.id), method: :post, data: {disable_with: '...'}
            .pull-left
              .fa.fa-plus.btn{'data-target': "#label_list_#{task.id}", 'data-toggle': 'modal'}
          %td.task_title
            = task.title
          %td.task_status
            = form_tag task_status_update_path do
              = hidden_field_tag :id, task.id
              = select_tag :status_select, options_for_select(task.transitionable_state_option_by, task.status), class: "status_select task_#{task.id}", onchange: "this.form.submit()"
          %td.task_priority
            = t("view.tasks.priorities.#{task.priority}")
          %td.task_end_period
            = task.end_period.strftime("%Y年 %m月 %d日")
          %td.task_created_at
            = task.created_at.strftime("%Y年 %m月 %d日")
          %td
            = link_to fa_icon('edit lg') , edit_task_path(task)
          %td
            = link_to fa_icon('trash lg') , task, method: :delete, data: { confirm: t('view.tasks.delete_confirm', title: task.title) }

.text-center
  = page_entries_info @tasks
  = paginate(@tasks)
= render 'search_form'

app/views/tasks/new.html.haml
- provide(:title, t('view.tasks.new_page'))

= render 'form'
= link_to t('view.tasks.back'), root_path, class: 'btn btn-default btn-block'