config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  post 'task_status_update', to: 'tasks#status_update'
  post 'add_label', to: 'tasks#add_label'
  post 'remove_label', to: 'tasks#remove_label'

  resources :labels  
  resources :users
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :admin do
    get '/', to: 'home#index'
    resources :users do
      resources :tasks, only: [:index]
    end
    resources :labels, only: [:index, :delete]
  end

  get '*anything', to: 'errors#routing_error'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_labels
  has_many :labels, through: :task_labels

  include AASM
  enum priority: {low: 0, normal: 1, high: 2}

  validates :title, :content, :end_period, :priority, presence: true
  validates :title, length: { maximum: 30 }
  validates :content, length: { maximum: 500 }
  validate :end_period_check, on: :create

  aasm column: :status do
    state :waiting,initial: true
    state :working 
    state :completed

    event :work do
      transitions from: :waiting, to: :working
    end

    event :complete do
      transitions from: :working, to: :completed
    end

  end

  def transitionable_state_option_by
    [[I18n.t("view.tasks.#{status}"), '']].concat(self.aasm.events.map(&:name).map{|state| [I18n.t("view.tasks.#{state}"), state] })
  end

  private

    def end_period_check
      if self.end_period.present?
        errors.add(:end_period, I18n.t('model.tasks.end_period_error_message')) unless self.end_period > Time.now
      end
    end
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < Admin::BaseController
  before_action :logged_in_user
  
  def index
   @user = User.find(params[:user_id])
   @q = @user.tasks.search(params[:q] || {s: 'created_at desc'})
   @tasks = @q.result(distinct: true).page(params[:page])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user
  before_action :load_task, only: [:edit, :destroy, :update, :status_update, :add_label, :remove_label]
  before_action :load_priorities, only: [:edit, :new, :create, :update]

  def index
    @q = current_user.tasks.includes(:labels).search(params[:q] || {s: 'created_at desc'})
    @tasks = @q.result(distinct: true).page(params[:page])
    @status = Task.aasm.states.map(&:name)
    @labels = Label.all
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = t('controller.tasks.create_message', title: @task.title)
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def update
    if @task.update_attributes(task_params)
      flash[:success] = t('controller.tasks.update_message', title: @task.title)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    flash[:success] = t('controller.tasks.destroy_message')
    redirect_to action: 'index'
  end

  def status_update
    @task.send(params[:status_select])
    @task.save!
    redirect_to action: 'index'
  end

  def add_label
    @task.task_labels.create(label_id: params[:label_id])
    redirect_to action: 'index'
  end

  def remove_label
    @task.task_labels.find_by(label_id: params[:label_id]).destroy
    redirect_to action: 'index'
  end

  private
    def task_params
      params.require(:task).permit(:title, :content, :end_period, :priority)
    end

    def load_task
      @task = Task.find(params[:id])
    end

    def load_priorities
      @priorities = Task.priorities.keys
    end  
  
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/tasks/index.html.haml
- provide(:title, "#{@user.name}の登録タスク一覧")
= link_to 'ユーザー一覧へ戻る', admin_users_path, class: 'btn btn-default pull-right'
= link_to t('view.tasks.clear'), request.path, class: "btn btn-default pull-right"
.task_list
  %table.table.table-striped.table-hover.table-responsive
    %thead
      %tr
        %th= sort_link(@q, :title, t('view.tasks.title')) 
        %th= t('view.tasks.status')
        %th= sort_link(@q, :priority, t('view.tasks.priority'))
        %th= sort_link(@q, :end_period, t('view.tasks.end_period'))
        %th= sort_link(@q, :created_at, t('view.tasks.created_at')) 
    %tbody
      - @tasks.each do |task|
        %tr
          %td.task_title
            = task.title
          %td.task_status
            = t("view.tasks.#{task.status}")
          %td.task_priority
            = t("view.tasks.priorities.#{task.priority}")
          %td.task_end_period
            = task.end_period.strftime("%Y年 %m月 %d日")
          %td.task_created_at
            = task.created_at.strftime("%Y年 %m月 %d日")

.text-center
  = page_entries_info @tasks
  = paginate(@tasks)