config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  post 'task_status_update', to: 'tasks#status_update'
  post 'add_label', to: 'tasks#add_label'
  post 'remove_label', to: 'tasks#remove_label'

  resources :labels  
  resources :users
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :admin do
    get '/', to: 'home#index'
    resources :users do
      resources :tasks, only: [:index]
    end
    resources :labels, only: [:index, :delete]
  end

  get '*anything', to: 'errors#routing_error'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  enum admin: { general: 0, admin: 1}

  attr_accessor :remember_token
  before_save   :downcase_email
  before_destroy :last_admin_do_not_delete

  has_secure_password validations: false
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  
  scope :admin_users, -> { where(admin: 'admin') }

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def authenticated?(token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(token)
  end

  def admin_user?
    self.admin == 'admin'
  end  

  def last_admin_user?
    self.admin_user? && User.admin_users.count == 1
  end  

  private

    def downcase_email
      email.downcase!
    end

    def last_admin_do_not_delete
      if last_admin_user?
        errors.add :base, '最後の管理者のため削除できません。他のユーザーにadminを付与して下さい。'
        throw :abort
      end
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, only: [:edit, :destroy, :update]
  before_action :load_role, only: [:edit, :update]

  def index
    @q = User.includes(:tasks).search(params[:q])
    @users = @q.result(distinct: true).page(params[:page])
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを作成しました。'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "#{@user.name}を更新しました。"
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "ユーザーを削除しました。"
    else
      flash[:danger] = "#{@user.errors.full_messages}"
    end
    redirect_to action: 'index'
  end

  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def load_user
      @user = User.find(params[:id])
    end  

    def load_role
      @roles = User.admins.keys
    end  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:info] = t('controller.users.login_message')
      redirect_to root_url
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_form.html.haml
= form_for [:admin, @user] do |f|
  = render 'shared/error_messages', object: f.object
  
  .form-group
    = f.label :name, t('view.users.name')
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :email, t('view.users.email')
    = f.email_field :email, class: 'form-control'

  - if controller.action_name == 'new' || controller.action_name == 'create'
    .form-group
      = f.label :password, t('view.users.password')
      = f.password_field :password, class: 'form-control'

    .form-group
      = f.label :password_confirmation, t('view.users.password_confirmation')
      = f.password_field :password_confirmation, class: 'form-control'
  
  - else
    .form-group
      = f.label :admin, '権限'
      = f.select :admin, @roles, class: 'form-control'

  = f.submit t('view.tasks.create'), class: 'btn btn-primary btn-block'

app/views/admin/users/edit.html.haml
- provide(:title, 'ユーザー編集')

= render 'form'
= link_to '一覧に戻る', admin_users_path, class: 'btn btn-default btn-block'

app/views/admin/users/index.html.haml
- provide(:title, '登録ユーザー一覧')

= link_to t('view.tasks.new'), new_admin_user_path, class: 'btn btn-primary pull-right'
.user_list
  %table.table.table-striped.table-hover.table-responsive
    %thead
      %tr
        %th= sort_link(@q, :id, 'ID') 
        %th= sort_link(@q, :name, '名前') 
        %th= sort_link(@q, :admin, '権限')
        %th= '作成タスク数'        
        %th= sort_link(@q, :created_at, '登録日時') 
        %th
        %th
    %tbody
      - @users.each do |user|
        = form_tag task_status_update_path do
          = hidden_field_tag :id, user.id
          %tr
            %td.user_id
              = user.id
            %td.user_name
              = user.name
            %td.user_admin
              = user.admin
            %td.user_tasks
              = link_to user.tasks.size, admin_user_tasks_path(user)
            %td.user_created_at
              = user.created_at.strftime("%Y年 %m月 %d日 %H時 %M分")
            %td= link_to '編集' , edit_admin_user_path(user)
            %td= link_to '削除' , [:admin, user], method: :delete, data: { confirm: "#{user.name}を削除しますか？" }
    
.text-center
  = page_entries_info @users
  = paginate(@users)

app/views/admin/users/new.html.haml
- provide(:title, 'ユーザー作成')

= render 'form'
= link_to '一覧に戻る', admin_users_path, class: 'btn btn-default btn-block'