config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  post 'task_status_update', to: 'tasks#status_update'
  post 'add_label', to: 'tasks#add_label'
  post 'remove_label', to: 'tasks#remove_label'

  resources :labels  
  resources :users
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  namespace :admin do
    get '/', to: 'home#index'
    resources :users do
      resources :tasks, only: [:index]
    end
    resources :labels, only: [:index, :delete]
  end

  get '*anything', to: 'errors#routing_error'
end

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    %nav
      %ul.nav.navbar-nav.navbar-right
        - if logged_in?
          %li= link_to 'タスク管理', root_path
          %li= link_to 'ラベル管理', labels_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
              アカウント
              %b.caret
            %ul.dropdown-menu
              %li= link_to '管理画面', admin_path
              %li.divider
              %li= link_to 'ログアウト', logout_path, method: :delete
        - else
          %li= link_to "ログイン", login_path

%h1.text-center.page-header
  = yield(:title)

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", 'http-equiv': "Content-Type"}/
    %title= yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'admin/base', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid
        .navbar-header
          = link_to 'El-Training', admin_path, class: 'navbar-brand'
    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          %ul.nav.nav-sidebar
            = sidebar_list_items
        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          %h1.page-header= yield(:title) if yield(:title)
          - flash.each do |message_type, message|
            = content_tag(:div, message, class: "alert alert-#{message_type}")
          = yield
          = debug(params) if Rails.env.development?

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= yield(:title)
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render 'layouts/header' 

      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
        
      = yield
      = debug(params) if Rails.env.development?